version: '3.8'
services:
  dev-db:
    image: postgres:latest
    environment:
      POSTGRES_DB: ${DEV_DB_NAME}
      POSTGRES_USER: ${DEV_DB_USER}
      POSTGRES_PASSWORD: ${DEV_DB_PASSWORD}
    ports:
      - "${DEV_DB_PORT}:5432"
    volumes:
      - dev-db-data:/var/lib/postgresql/data

  test-db:
    image: postgres:latest
    environment:
      POSTGRES_DB: ${TEST_DB_NAME}
      POSTGRES_USER: ${TEST_DB_USER}
      POSTGRES_PASSWORD: ${TEST_DB_PASSWORD}
    ports:
      - "${TEST_DB_PORT}:5432"
    volumes:
      - test-db-data:/var/lib/postgresql/data

volumes:
  dev-db-data:
  test-db-data: